# Site settings
title: Scotland
client:
  name: VisitScotland
  link: "https://www.visitscotland.com"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  As winter turns to spring, the sweeping landscapes of Scotland begin to shine with life once more - there’s simply no better time to visit Scotland.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/scotland" # the subpath of your site, e.g. /blog/
img:     "/scotland/_assets/img"
css:     "/scotland/_assets/css"
js:      "/scotland/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed